site_name: StaX Documentation
site_description: Official documentation for the StaX project.
site_url: #https://stax.example.com
repo_url: #https://github.com/stax/stax
navigation:
  - Home: index.md
  - Overview: README.md
  - Documentation: documentation.md
  - User Guide: user-guide.md
theme:
  name: material